language: php

php:
  - 5.4
  - 5.5

env:
  - NETCOMMONS_VERSION=master DB=mysql
  - NETCOMMONS_VERSION=master DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - export PLUGIN_NAME=`basename $TRAVIS_BUILD_DIR`
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - cp -r ../$PLUGIN_NAME plugins
  - cp -r ../$PLUGIN_NAME app/Plugin/
  - chmod -R 777 app/tmp
  - mkdir -p build/logs
  - pear channel-discover pear.phpunit.de
  - pear config-set auto_discover 1; pear install --alldeps phpunit/PHPUnit-3.7.32
  - pear channel-discover pear.cakephp.org
  - pear install --alldeps cakephp/CakePHP_CodeSniffer
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install phpmd/PHP_PMD
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/phpcpd
  - phpenv rehash
  - set +H
  - cp app/Config/database.php.test app/Config/database.php
  - for p in `cat app/Config/vendors.txt`; do export IGNORE_PLUGINS=$IGNORE_PLUGINS,$TRAVIS_BUILD_DIR/app/Plugin/$p; export IGNORE_PLUGINS_OPTS="$IGNORE_PLUGINS_OPTS --exclude app/Plugin/$p"; done
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - npm install -g bower
  - bower install
  - npm install jasmine-node karma karma-coverage karma-jasmine karma-firefox-launcher karma-phantomjs-launcher


script:
  - ./lib/Cake/Console/cake test $PLUGIN_NAME All$PLUGIN_NAME --stderr
  - phpcs -p --extensions=php --standard=CakePHP --ignore=app/Config/Migration/,app/Config/database.php,$IGNORE_PLUGINS app
  - phpmd app text ruleset/phpmd.xml --exclude $NETCOMMONS_BUILD_DIR/app/Config/Migration,$IGNORE_PLUGINS
  - phpcpd --exclude Test --exclude Config --exclude app/Config/database.php $IGNORE_PLUGINS_OPTS app
  - ./node_modules/karma/bin/karma  start Plugin/ThemeSettings/JavascriptTest/travis.karma.conf.js --single-run --browsers PhantomJS

after_script:
  - php vendors/bin/coveralls -vvv

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
